import { mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';

export interface GenerateApiClientOptions {
  /** Caminho de saída relativo ao cwd, ex: 'src/lib/apiClient.ts' */
  outputPath?: string;
  /**
   * Nome do cookie que contém o JWT.
   * Se não passado, o interceptor de auth é gerado mas não lê nenhum cookie.
   */
  cookieName?: string;
  /**
   * Redirect path quando recebe 401.
   * @default '/auth'
   */
  unauthorizedRedirect?: string;
  /** Incluir headers de device tracking (deviceId, userAgent, etc.) */
  deviceTracking?: boolean;
}

/**
 * Gera o apiClient.ts — cliente axios para o frontend (browser).
 *
 * O client:
 *  - Lê o JWT do cookie `cookieName` (se configurado) e o envia como Bearer
 *  - Redireciona para `unauthorizedRedirect` em caso de 401
 *  - Opcionalmente injeta headers de device tracking
 */
export function generateApiClient({
  outputPath = 'src/lib/apiClient.ts',
  cookieName,
  unauthorizedRedirect = '/auth',
  deviceTracking = false,
}: GenerateApiClientOptions, cwd: string): string {
  const hasCookie = !!cookieName;

  const cookieImport = hasCookie ? `import Cookies from 'js-cookie';\n` : '';

  const authBlock = hasCookie
    ? `
  const token = Cookies.get('${cookieName}');
  if (token) {
    config.headers.Authorization = \`Bearer \${token}\`;
  }`
    : `
  // cookieName não configurado — nenhum token será enviado automaticamente.
  // Para autenticar manualmente, chame: apiClient.defaults.headers.common['Authorization'] = 'Bearer <token>';`;

  const deviceBlock = deviceTracking
    ? `
  if (typeof window !== 'undefined') {
    let deviceId = 'unknown';
    try {
      deviceId = localStorage.getItem('deviceId') ?? '';
      if (!deviceId) {
        deviceId = crypto.randomUUID?.() ?? Math.random().toString(36).slice(2) + Date.now().toString(36);
        localStorage.setItem('deviceId', deviceId);
      }
    } catch (_) {}

    const ua = window.navigator.userAgent;
    const isMobile = /iPhone|iPad|iPod|Android/i.test(ua);
    config.headers['x-device-id']         = deviceId;
    config.headers['x-device-user-agent'] = ua;
    config.headers['x-device-browser']    = ua.includes('Chrome') ? 'Chrome' : ua.includes('Safari') ? 'Safari' : 'Other';
    config.headers['x-device-os']         = ua.includes('Windows') ? 'Windows' : ua.includes('Mac') ? 'MacOS' : 'Other';
    config.headers['x-device-type']       = isMobile ? 'mobile' : 'desktop';
  }`
    : '';

  const removeCookie = hasCookie
    ? `      Cookies.remove('${cookieName}');`
    : '      // Limpe manualmente os dados de sessão aqui se necessário.';

  const content = `// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import axios from 'axios';
${cookieImport}
const apiClient = axios.create({
  baseURL: '',
});

apiClient.interceptors.request.use(
  (config) => {${authBlock}${deviceBlock}
    return config;
  },
  (error) => Promise.reject(error),
);

apiClient.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
${removeCookie}
      if (typeof window !== 'undefined') {
        window.location.href = '${unauthorizedRedirect}';
      }
    }
    return Promise.reject(error);
  },
);

export default apiClient;
`;

  const absolutePath = join(cwd, outputPath);
  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, content, 'utf-8');
  return outputPath;
}
