import { mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import {
  buildPathTree,
  toNextPathWithTree,
  buildParamMap,
  extractOperations,
  fetchSpec,
  lineComment,
  relativeImport,
  stringLiteral,
} from './utils.js';

/** Backend URL template for a spec path, e.g. /users/{id} → `${API_URL}/users/${encodeURIComponent(params.id)}` */
export function buildBackendPath(path: string, paramMap: Record<string, string>, paramsVar: string) {
  return path.replace(/\{(\w+)\}/g, (_, p) => `\${encodeURIComponent(${paramsVar}.${paramMap[p] ?? p})}`);
}

/**
 * Renders one route.ts. Every method of a path shares the same backend URL, so a single
 * `proxy` function forwards the request untouched (method, headers, body, query string)
 * and returns the backend response as-is (status, headers, Set-Cookie, JSON or binary body).
 */
function renderRoute({ operations, apiEnvVar, apiFallback, fetchBackendImport }: any) {
  const summaries = operations
    .map((op: any) => `// ${op.method} ${op.path}${op.summary ? ` — ${lineComment(op.summary)}` : ''}`)
    .join('\n');

  const [first] = operations;
  const hasPathParams = first.pathParams.length > 0;
  const backendPath = buildBackendPath(first.path, first.paramMap, 'params');
  const methods: string[] = [...new Set<string>(operations.map((op: any) => op.method))];

  return `// Auto-generated by codegen-openapi — do not edit manually
import { fetchBackend, forwardHeaders, readBody, toResponse } from '${fetchBackendImport}';

${summaries}

async function proxy(request: Request${hasPathParams ? ', context: any' : ''}) {
  try {
    const API_URL = process.env.${apiEnvVar} || ${stringLiteral(apiFallback ?? '')};${hasPathParams ? `
    const params = await context.params;` : ''}
    const { search } = new URL(request.url);

    const response = await fetchBackend(\`\${API_URL}${backendPath}\${search}\`, {
      method: request.method,
      headers: await forwardHeaders(request),
      body: request.method === 'GET' ? undefined : await readBody(request),
    });
    return toResponse(response);
  } catch (error) {
    console.error(\`[\${request.method} ${first.path}]\`, error);
    return Response.json({ success: false, message: 'Internal Server Error' }, { status: 500 });
  }
}

${methods.map((m) => `export const ${m} = proxy;`).join('\n')}
`;
}

/** Lists the route.ts files generateRoutes() would write, without touching the disk. */
export function planRoutes({ spec, stripPathPrefix, routesOut }: any) {
  const operations = extractOperations(spec, { stripPathPrefix });
  const tree = buildPathTree(operations.map((op: any) => op.path));

  // Group by Next.js path (multiple methods mapping to the same route.ts file)
  const byFile = new Map<string, any[]>();
  for (const op of operations) {
    const file = join(routesOut, toNextPathWithTree(op.path, tree), 'route.ts');
    if (!byFile.has(file)) byFile.set(file, []);
    byFile.get(file)!.push({ ...op, paramMap: buildParamMap(op.path, tree) });
  }
  return byFile;
}

export async function generateRoutes({
  spec,
  stripPathPrefix,
  apiEnvVar,
  apiFallback,
  routesOut,
  fetchBackendPath,
  fetchBackendFile = 'src/lib/fetchBackend.ts',
  cwd,
}: any) {
  const parsed = typeof spec === 'string' ? await fetchSpec(spec) : spec;
  const files: string[] = [];

  for (const [relativePath, ops] of planRoutes({ spec: parsed, stripPathPrefix, routesOut })) {
    // An explicit fetchBackendPath wins (e.g. '@/lib/fetchBackend'); otherwise import relatively
    const fetchBackendImport = fetchBackendPath ?? relativeImport(dirname(relativePath), fetchBackendFile);
    const content = renderRoute({ operations: ops, apiEnvVar, apiFallback, fetchBackendImport });

    const absolutePath = join(cwd, relativePath);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, content, 'utf-8');
    files.push(relativePath);
  }

  return files;
}
