import { mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import {
  buildPathTree,
  toNextPathWithTree,
  buildParamMap,
  extractOperations,
  fetchSpec,
  lineComment,
  relativeImport,
  stringLiteral,
} from './utils.js';
import { buildBackendPath } from './generateRoutes.js';

/**
 * Renders one Pages Router API route. Every method of a path shares the same backend URL, so the
 * handler forwards the request untouched (method, headers, raw body, query string) and sends the
 * backend response back as-is (status, headers, Set-Cookie, JSON or binary body).
 */
function renderPagesHandler({ operations, apiEnvVar, apiFallback, fetchBackendImport }: any) {
  const summaries = operations
    .map((op: any) => `// ${op.method} ${op.path}${op.summary ? ` — ${lineComment(op.summary)}` : ''}`)
    .join('\n');

  const [first] = operations;
  const paramNames: string[] = first.pathParams.map((p: string) => first.paramMap[p] ?? p);
  const backendPath = buildBackendPath(first.path, first.paramMap, 'params');
  const methods: string[] = [...new Set<string>(operations.map((op: any) => op.method))];

  const paramsLine = paramNames.length
    ? `\n    const params = req.query as { ${paramNames.map((p) => `${p}: string`).join('; ')} };`
    : '';

  return `// Auto-generated by codegen-openapi — do not edit manually
import type { NextApiRequest, NextApiResponse } from 'next';
import { fetchBackend, forwardHeaders, readBody, sendResponse } from '${fetchBackendImport}';

${summaries}

// Bodies are forwarded untouched (JSON, multipart, binary), so Next's body parser stays off
export const config = { api: { bodyParser: false } };

const ALLOWED_METHODS = [${methods.map((m) => `'${m}'`).join(', ')}];

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (!ALLOWED_METHODS.includes(req.method ?? '')) {
    res.setHeader('Allow', ALLOWED_METHODS.join(', '));
    return res.status(405).json({ success: false, message: 'Method Not Allowed' });
  }

  try {
    const API_URL = process.env.${apiEnvVar} || ${stringLiteral(apiFallback ?? '')};${paramsLine}
    const search = req.url?.includes('?') ? req.url.slice(req.url.indexOf('?')) : '';

    const response = await fetchBackend(\`\${API_URL}${backendPath}\${search}\`, {
      method: req.method,
      headers: forwardHeaders(req),
      body: req.method === 'GET' ? undefined : await readBody(req),
    });
    return sendResponse(res, response);
  } catch (error) {
    console.error(\`[\${req.method} ${first.path}]\`, error);
    return res.status(500).json({ success: false, message: 'Internal Server Error' });
  }
}
`;
}

/**
 * Converts a Next.js path (e.g. /users/[id]/posts) to a Pages Router file path.
 * /users/[id] → users/[id].ts
 * /users      → users.ts
 * /users/[id]/posts → users/[id]/posts.ts
 */
export function nextPathToPageFilePath(nextPath: string): string {
  const segs = nextPath.split('/').filter(Boolean);
  if (segs.length === 0) return 'index.ts';
  const last = segs[segs.length - 1];
  const dirs = segs.slice(0, -1);
  return [...dirs, last + '.ts'].join('/');
}

/** Lists the API route files generateRoutesPages() would write, without touching the disk. */
export function planRoutesPages({ spec, stripPathPrefix, routesOut }: any) {
  const operations = extractOperations(spec, { stripPathPrefix });
  const tree = buildPathTree(operations.map((op: any) => op.path));

  // Group operations by output file (multiple methods → one handler file)
  const byFile = new Map<string, any[]>();
  for (const op of operations) {
    const file = join(routesOut, nextPathToPageFilePath(toNextPathWithTree(op.path, tree)));
    if (!byFile.has(file)) byFile.set(file, []);
    byFile.get(file)!.push({ ...op, paramMap: buildParamMap(op.path, tree) });
  }
  return byFile;
}

export async function generateRoutesPages({
  spec,
  stripPathPrefix,
  apiEnvVar,
  apiFallback,
  routesOut,
  fetchBackendPath,
  fetchBackendFile = 'src/lib/fetchBackend.ts',
  cwd,
}: any) {
  const parsed = typeof spec === 'string' ? await fetchSpec(spec) : spec;
  const files: string[] = [];

  for (const [relativePath, ops] of planRoutesPages({ spec: parsed, stripPathPrefix, routesOut })) {
    // An explicit fetchBackendPath wins (e.g. '@/lib/fetchBackend'); otherwise import relatively
    const fetchBackendImport = fetchBackendPath ?? relativeImport(dirname(relativePath), fetchBackendFile);
    const content = renderPagesHandler({ operations: ops, apiEnvVar, apiFallback, fetchBackendImport });

    const absolutePath = join(cwd, relativePath);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, content, 'utf-8');
    files.push(relativePath);
  }

  return files;
}
