import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import {
  normalizeParamName,
  operationIdToMethodName,
  slugifyTag,
  extractOperations,
  fetchSpec,
  getSuccessResponseSchema,
} from './utils.js';

// ─── Aliases (mirrors generateServices.ts pattern) ────────────────────────────

function pascal(str: string) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function getAliases(op: any) {
  const name = operationIdToMethodName(op.operationId);
  const P = pascal(name);
  return {
    methodName: name,
    hookName: `use${pascal(name)}`,
    aliasResponse: `${P}Response`,
    aliasBody: op.hasBody ? `${P}Body` : null,
    aliasParams: op.hasQueryParams ? `${P}Params` : null,
  };
}

// ─── Hook renderer ────────────────────────────────────────────────────────────

function renderQueryHook(op: any, serviceVarName: string) {
  const { methodName, hookName, aliasResponse, aliasParams } = getAliases(op);
  const { path, pathParams, hasQueryParams, summary } = op;

  const normalizedParams: string[] = pathParams.map((p: string) =>
    normalizeParamName(p, pathParams),
  );

  // Build function arguments
  const args: string[] = [];
  normalizedParams.forEach((p: string) => args.push(`${p}: string`));
  if (aliasParams && hasQueryParams) args.push(`params?: ${aliasParams}`);

  // Build queryKey: ['tag', param1, param2, ...]
  const queryKeyItems = ['tag', ...normalizedParams.map((p) => p)];
  if (aliasParams && hasQueryParams) queryKeyItems.push('params');
  const queryKey = `[${queryKeyItems.join(', ')}]`;

  // Build service call args
  const serviceArgs = [...normalizedParams];
  if (aliasParams && hasQueryParams) serviceArgs.push('params');

  const enabled = normalizedParams.length > 0
    ? `\n    enabled: ${normalizedParams.map((p) => `!!${p}`).join(' && ')},`
    : '';

  const comment = summary ? `/** ${summary} */\n` : '';

  return `${comment}export function ${hookName}(${args.join(', ')}) {
  return useQuery<${aliasResponse}>({
    queryKey: ${queryKey},
    queryFn: () => ${serviceVarName}.${methodName}(${serviceArgs.join(', ')}),${enabled}
  });
}`;
}

function renderMutationHook(op: any, serviceVarName: string, tagKey: string) {
  const { methodName, hookName, aliasResponse, aliasBody } = getAliases(op);
  const { pathParams, hasBody, summary } = op;

  const normalizedParams: string[] = pathParams.map((p: string) =>
    normalizeParamName(p, pathParams),
  );

  // Mutation variables type: combine path params + body
  const varFields: string[] = [];
  normalizedParams.forEach((p: string) => varFields.push(`${p}: string`));
  if (aliasBody && hasBody) varFields.push(`body: ${aliasBody}`);

  const varsType = varFields.length > 0 ? `{ ${varFields.join('; ')} }` : 'void';

  // Build service call args from variables
  const serviceArgs: string[] = [];
  normalizedParams.forEach((p: string) => serviceArgs.push(`vars.${p}`));
  if (aliasBody && hasBody) serviceArgs.push('vars.body');

  const mutationFn = varFields.length > 0
    ? `(vars: ${varsType}) => ${serviceVarName}.${methodName}(${serviceArgs.join(', ')})`
    : `() => ${serviceVarName}.${methodName}()`;

  const comment = summary ? `/** ${summary} */\n` : '';

  return `${comment}export function ${hookName}() {
  const queryClient = useQueryClient();
  return useMutation<${aliasResponse}, Error, ${varsType}>({
    mutationFn: ${mutationFn},
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [${tagKey}] });
    },
  });
}`;
}

// ─── Hooks file renderer ──────────────────────────────────────────────────────

function renderHooksFile({ tag, slug, operations, servicesOut }: any) {
  const serviceVarName = slugToCamel(slug) + 'Service';
  const tagKey = JSON.stringify(slug);

  const typeImports: string[] = [];
  for (const op of operations) {
    const { aliasResponse, aliasBody, aliasParams } = getAliases(op);
    typeImports.push(aliasResponse);
    if (aliasBody) typeImports.push(aliasBody);
    if (aliasParams) typeImports.push(aliasParams);
  }

  const hooks = operations
    .map((op: any) => {
      const isGet = op.method === 'GET';
      return isGet
        ? renderQueryHook(op, serviceVarName)
        : renderMutationHook(op, serviceVarName, tagKey);
    })
    .join('\n\n');

  return `// Auto-generated by codegen-openapi — do not edit manually
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import ${serviceVarName} from '${servicesOut}/${slug}';
import type { ${typeImports.join(', ')} } from '${servicesOut}/${slug}/types';

const tag = ${tagKey};

${hooks}
`;
}

function slugToCamel(slug: string) {
  return slug
    .split('-')
    .map((w: string, i: number) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
    .join('');
}

// ─── Entry point ──────────────────────────────────────────────────────────────

export async function generateHooks({
  spec,
  stripPathPrefix,
  hooksOut,
  servicesOut,
  cwd,
}: any) {
  const parsed = typeof spec === 'string' ? await fetchSpec(spec) : spec;
  const operations = extractOperations(parsed, { stripPathPrefix });

  const byTag = new Map<string, any[]>();
  for (const op of operations) {
    const tag = op.tags[0] ?? 'default';
    if (!byTag.has(tag)) byTag.set(tag, []);
    byTag.get(tag)!.push(op);
  }

  const files: string[] = [];

  for (const [tag, ops] of byTag) {
    const slug = slugifyTag(tag);
    mkdirSync(join(cwd, hooksOut, slug), { recursive: true });

    const hooksFile = join(hooksOut, slug, 'index.ts');
    writeFileSync(
      join(cwd, hooksFile),
      renderHooksFile({ tag, slug, operations: ops, servicesOut }),
      'utf-8',
    );
    files.push(hooksFile);
  }

  return files;
}
