import { mkdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';

export interface GenerateFetchBackendOptions {
  /** Caminho de saída relativo ao cwd, ex: 'src/lib/fetchBackend.ts' */
  outputPath?: string;
  /**
   * Nome do cookie que contém o JWT.
   * Se configurado, o fetchBackend também lê esse cookie e envia como Bearer
   * nas chamadas server-side (usando `cookies()` do Next.js).
   */
  cookieName?: string;
  /**
   * Timeout em ms para as chamadas ao backend.
   * @default 15000
   */
  timeout?: number;
}

/**
 * Gera o fetchBackend.ts — cliente HTTP server-side (Next.js Route Handlers).
 *
 * O client:
 *  - Usa axios para ser compatível com o BACKEND_IGNORE_SSL no dev
 *  - Retorna uma interface compatível com fetch() para não quebrar os route handlers gerados
 *  - Se `cookieName` configurado, lê o cookie via next/headers e envia como Bearer
 */
export function generateFetchBackend({
  outputPath = 'src/lib/fetchBackend.ts',
  cookieName,
  timeout = 15_000,
}: GenerateFetchBackendOptions, cwd: string): string {
  const hasCookie = !!cookieName;

  const cookieBlock = hasCookie
    ? `
  // Propaga o JWT do cookie nas chamadas server-side (Route Handlers)
  const { cookies } = await import('next/headers');
  const cookieStore = await cookies();
  const token = cookieStore.get('${cookieName}')?.value;
  if (token && !headers['Authorization'] && !headers['authorization']) {
    headers['Authorization'] = \`Bearer \${token}\`;
  }`
    : `
  // cookieName não configurado — nenhum JWT é propagado automaticamente.
  // Se precisar, passe o header Authorization manualmente na chamada.`;

  const content = `// Auto-generated by kubb-plugin-nextjs-routes — do not edit manually
import 'server-only';
import axios from 'axios';
import https from 'node:https';

const httpsAgent =
  process.env.BACKEND_IGNORE_SSL === 'true'
    ? new https.Agent({ rejectUnauthorized: false })
    : undefined;

export interface FetchBackendOptions {
  method?: string;
  headers?: Record<string, string>;
  body?: unknown;
}

/**
 * Faz uma chamada HTTP ao backend a partir de um Route Handler do Next.js.
 * Retorna um objeto com interface similar ao fetch() para compatibilidade.
 */
export async function fetchBackend(
  url: string,
  { method = 'GET', headers = {}, body }: FetchBackendOptions = {},
) {
  // Garante que headers seja mutável
  headers = { ...headers };
${cookieBlock}

  const response = await axios({
    url,
    method,
    headers,
    data: body,
    httpsAgent,
    timeout: ${timeout},
    validateStatus: () => true,
  });

  return {
    ok: response.status >= 200 && response.status < 300,
    status: response.status,
    headers: {
      get: (key: string) => (response.headers[key.toLowerCase()] as string) ?? null,
    },
    json: async () => response.data as unknown,
    text: async () =>
      typeof response.data === 'string'
        ? response.data
        : JSON.stringify(response.data),
  };
}
`;

  const absolutePath = join(cwd, outputPath);
  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, content, 'utf-8');
  return outputPath;
}
